### ISSUE TITLE
NLP Tutorial notebooks for Biomegatron-bert

### ISSUE THREAD

**Issue by avikpal00** [NVIDIA/NeMo#1554]
**Describe the bug**

Not able to download and initialize the pretrained biomegatron bert model.

config.model.language_model.pretrained_model_name = "biomegatron-bert-345m-cased"
Error Line: nemo_nlp.models.TokenClassificationModel(cfg=config.model, trainer=trainer)

Error: 'OSError: Distant resource does not have an ETag, we won't be able to reliably ensure reproducibility.'

But, I don't get any error if I replace the pre-trained model to a Megatron model ("megatron-bert-345m-cased").
Since the architecture of both models are same I would only assume there is some sort of error in packaging of the biomegatron model.

**Expected behavior**

The notebook to run without any error.

**Environment overview (please complete the following information)**

 - Environment location: Google Colab
 - Tutorial Notebook - https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/nlp/Token_Classification-BioMegatron.ipynb
 - Changed transformers version from 4.0.0 to 3.5.0. (I downgraded the version as it seems that the notebook was built on an older version of transformers and I kept getting ModuleNotFoundError because of module name changes in the newer version)

**Environment details**

- Python version = 3.6.9
- Transformers version = 3.5.0

**Comment by ekmb** [comment]
@avikpal00 thank you for reporting the issue. PR #1558 should fix it, no need to change the transformers version.

**Comment by meetdave06** [comment]
@ekmb I am still getting this error for the tutorial notebook [Token_Classification-BioMegatron.ipynb](https://colab.research.google.com/github/NVIDIA/NeMo/blob/r1.0.0b3/tutorials/nlp/Token_Classification-BioMegatron.ipynb) when I try to use "biomegatron-bert-345m-cased".

<img width="1086" alt="Screen Shot 2021-01-05 at 7 10 01 PM" src="https://user-images.githubusercontent.com/7240751/103713149-9f7fd180-4f89-11eb-9ec5-b4170ab1773a.png">
