### ISSUE TITLE
ASR_with_NeMo Pre-trained Model Inference | Pickling Error 

### ISSUE THREAD

**Issue by sorenjmadsen** [NVIDIA/NeMo#3441]
**Describe the bug**
On attempting inference of a recording, I received the following error:
PicklingError: Can't pickle <class 'nemo.collections.common.parts.preprocessing.collections.AudioTextEntity'>: attribute lookup AudioTextEntity on nemo.collections.common.parts.preprocessing.collections failed

**Steps/Code to reproduce bug**

```
import nemo
import nemo.collections.asr as nemo_asr
asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En", strict=False)

files = ['./soundsample.wav']
for fname, transcription in zip(files, asr_model.transcribe(paths2audio_files=files)):
  print(f"Audio in {fname} was recognized as: {transcription}")
```

**Environment overview**
 - Conda Virtual Environment
 - Method of NeMo install: from source

**Environment details**
- Mac OS Catalina 10.15.7
- PyTorch version: 1.10.1
- Python version: 3.8.5

**Comment by titu1994** [comment]
Nemo models and datasets are not pickleabl - we recommend using ddp in all cases when training. 

However I don't know why it's occuring during inference - are you trying to launch that code on multiple threads ? That will not work. You need different processes independent from each other.

**Comment by sorenjmadsen** [comment]
The above snippet is all I am trying to run. The pickle error is thrown when I call transcribe().

**Comment by sorenjmadsen** [comment]
Stack trace:
```
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
Input In [4], in <module>
      1 asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En", strict=False)
      3 files = ['./soundsample.wav']
----> 4 for fname, transcription in zip(files, asr_model.transcribe(paths2audio_files=files)):
      5   print(f"Audio in {fname} was recognized as: {transcription}")

File ~/opt/anaconda3/envs/nemo/lib/python3.9/site-packages/torch/autograd/grad_mode.py:28, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     25 @functools.wraps(func)
     26 def decorate_context(*args, **kwargs):
     27     with self.__class__():
---> 28         return func(*args, **kwargs)

File ~/Documents/MetaSense.ai/NeMo/nemo/collections/asr/models/ctc_models.py:268, in EncDecCTCModel.transcribe(self, paths2audio_files, batch_size, logprobs, return_hypotheses, num_workers)
    260 config = {
    261     'paths2audio_files': paths2audio_files,
    262     'batch_size': batch_size,
    263     'temp_dir': tmpdir,
    264     'num_workers': num_workers,
    265 }
    267 temporary_datalayer = self._setup_transcribe_dataloader(config)
--> 268 for test_batch in tqdm(temporary_datalayer, desc="Transcribing"):
    269     logits, logits_len, greedy_predictions = self.forward(
    270         input_signal=test_batch[0].to(device), input_signal_length=test_batch[1].to(device)
    271     )
    272     if logprobs:
    273         # dump log probs per file

File ~/opt/anaconda3/envs/nemo/lib/python3.9/site-packages/tqdm/notebook.py:231, in tqdm_notebook.__init__(self, *args, **kwargs)
    229 colour = kwargs.pop('colour', None)
    230 display_here = kwargs.pop('display', True)
--> 231 super(tqdm_notebook, self).__init__(*args, **kwargs)
    232 if self.disable or not kwargs['gui']:
    233     self.disp = lambda *_, **__: None

File ~/opt/anaconda3/envs/nemo/lib/python3.9/site-packages/tqdm/asyncio.py:33, in tqdm_asyncio.__init__(self, iterable, *args, **kwargs)
     31     self.iterable_next = iterable.__next__
     32 else:
---> 33     self.iterable_iterator = iter(iterable)
     34     self.iterable_next = self.iterable_iterator.__next__

File ~/opt/anaconda3/envs/nemo/lib/python3.9/site-packages/torch/utils/data/dataloader.py:359, in DataLoader.__iter__(self)
    357     return self._iterator
    358 else:
--> 359     return self._get_iterator()

File ~/opt/anaconda3/envs/nemo/lib/python3.9/site-packages/torch/utils/data/dataloader.py:305, in DataLoader._get_iterator(self)
    303 else:
    304     self.check_worker_number_rationality()
--> 305     return _MultiProcessingDataLoaderIter(self)

File ~/opt/anaconda3/envs/nemo/lib/python3.9/site-packages/torch/utils/data/dataloader.py:918, in _MultiProcessingDataLoaderIter.__init__(self, loader)
    911 w.daemon = True
    912 # NB: Process.start() actually take some time as it needs to
    913 #     start a process and pass the arguments over via a pipe.
    914 #     Therefore, we only add a worker to self._workers list after
    915 #     it started, so that we do not call .join() if program dies
    916 #     before it starts, and __del__ tries to join but will get:
    917 #     AssertionError: can only join a started process.
--> 918 w.start()
    919 self._index_queues.append(index_queue)
    920 self._workers.append(w)

File ~/opt/anaconda3/envs/nemo/lib/python3.9/multiprocessing/process.py:121, in BaseProcess.start(self)
    118 assert not _current_process._config.get('daemon'), \
    119        'daemonic processes are not allowed to have children'
    120 _cleanup()
--> 121 self._popen = self._Popen(self)
    122 self._sentinel = self._popen.sentinel
    123 # Avoid a refcycle if the target function holds an indirect
    124 # reference to the process object (see bpo-30775)

File ~/opt/anaconda3/envs/nemo/lib/python3.9/multiprocessing/context.py:224, in Process._Popen(process_obj)
    222 @staticmethod
    223 def _Popen(process_obj):
--> 224     return _default_context.get_context().Process._Popen(process_obj)

File ~/opt/anaconda3/envs/nemo/lib/python3.9/multiprocessing/context.py:284, in SpawnProcess._Popen(process_obj)
    281 @staticmethod
    282 def _Popen(process_obj):
    283     from .popen_spawn_posix import Popen
--> 284     return Popen(process_obj)

File ~/opt/anaconda3/envs/nemo/lib/python3.9/multiprocessing/popen_spawn_posix.py:32, in Popen.__init__(self, process_obj)
     30 def __init__(self, process_obj):
     31     self._fds = []
---> 32     super().__init__(process_obj)

File ~/opt/anaconda3/envs/nemo/lib/python3.9/multiprocessing/popen_fork.py:19, in Popen.__init__(self, process_obj)
     17 self.returncode = None
     18 self.finalizer = None
---> 19 self._launch(process_obj)

File ~/opt/anaconda3/envs/nemo/lib/python3.9/multiprocessing/popen_spawn_posix.py:47, in Popen._launch(self, process_obj)
     45 try:
     46     reduction.dump(prep_data, fp)
---> 47     reduction.dump(process_obj, fp)
     48 finally:
     49     set_spawning_popen(None)

File ~/opt/anaconda3/envs/nemo/lib/python3.9/multiprocessing/reduction.py:60, in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)

**Comment by titu1994** [comment]
Huh. I think it was a mistake to make the data loader use more than one worker by default. Can you put your code under a if __name__ == "__main__" block and try ? 

Otherwise another option is pass num_workers=0 to transcribe()

**Comment by sorenjmadsen** [comment]
When I put it under the conditional, it didn't run at all. However, setting the num_workers parameter worked! Thank you!

**Comment by nithinraok** [comment]
Can you provide a notebook to reproduce the error?

**Comment by JenyaPu** [comment]
Hello! The issue was solved when I updated nemo-toolkit with the following command:
`python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[asr]`
It allowed me to specify num_workers: 0 in the "ClusterDiarizer" manifest to avoid the following error, which occurs when a number of workers exceeds 0:
`_pickle.PicklingError: Can't pickle <class 'nemo.collections.common.parts.preprocessing.collections.SpeechLabelEntity'>: attribute lookup SpeechLabelEntity on nemo.collections.common.parts.preprocessing.collections failed`

**Comment by Harshada-Mule21** [comment]
when I going to update toolkit 'python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[asr]'
getting below error: INFO: pip is looking at multiple versions of nemo-toolkit[asr] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement triton (from nemo-toolkit[asr]) (from versions: none)
ERROR: No matching distribution found for triton

**Comment by Harshada-Mule21** [comment]
After updating toolkit ...still getting PicklingError: Can't pickle <class 'nemo.collections.common.parts.preprocessing.collections.SpeechLabelEntity'>: attribute lookup SpeechLabelEntity on nemo.collections.common.parts.preprocessing.collections failed

**Comment by MatiasCaccia** [comment]
Is there a solution for this error?

**Comment by MonolithFoundation** [comment]
Same error....

I suddendly knows why Linus have a word to Nvidia.
