### ISSUE TITLE
error running offline_diarization.py

### ISSUE THREAD

**Issue by RezaBi** [NVIDIA/NeMo#4192]
**Describe the bug**

Hi, I have previously run the code as stated in Usage description of the script. However, now I get this error by running the exact same code. This is the error messege.
Global seed set to 42
Traceback (most recent call last):
  File "/content/NeMo/examples/speaker_tasks/diarization/offline_diarization.py", line 46, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/nemo/core/config/hydra_runner.py", line 108, in wrapper
    config_name=config_name,
TypeError: _run_hydra() missing 1 required positional argument: 'args'

**Steps/Code to reproduce bug**

!python3 /content/NeMo/examples/speaker_tasks/diarization/offline_diarization.py \
diarizer.manifest_filepath='/content/input_manifest.json' \
diarizer.out_dir='demo_output' \
diarizer.speaker_embeddings.model_path='titanet_large' \
diarizer.oracle_vad=True

**Environment overview (please complete the following information)**

On Google colab

**Environment details**

**Comment by nithinraok** [comment]
This should fix the issue https://github.com/NVIDIA/NeMo/pull/4202 . 

Reinstall and you should be good.

**Comment by RezaBi** [comment]
Thanks for your response.
Nope, its still not working. the same issue still remains ( using branch 1.8.2). on which version did you test and resolve the issue?

**Comment by BSen007** [comment]
same issue here!

**Comment by nithinraok** [comment]
@titu1994 what version is the fix provided in?

**Comment by BSen007** [comment]
`pip install hydra-core==1.1` solved the issue for me
